// <auto-generated />
namespace DIPLOM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _return : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_return));
        
        string IMigrationMetadata.Id
        {
            get { return "202006071929388_return"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
